// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaq0qjLgS3TGrJnT07t0C9qeJiAH4Qwpw',
    appId: '1:775502867741:web:ea3e9a83ea95c9eaf585f4',
    messagingSenderId: '775502867741',
    projectId: 'bloguygfirebase',
    authDomain: 'bloguygfirebase.firebaseapp.com',
    storageBucket: 'bloguygfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfcVBaDdPpasfiRdhX9p6df9zNsDiWvek',
    appId: '1:775502867741:android:42f85a4df29b3614f585f4',
    messagingSenderId: '775502867741',
    projectId: 'bloguygfirebase',
    storageBucket: 'bloguygfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvggc7ZmlkIkoXJiZT_idPRAstA2b6eeg',
    appId: '1:775502867741:ios:d95126495db09edaf585f4',
    messagingSenderId: '775502867741',
    projectId: 'bloguygfirebase',
    storageBucket: 'bloguygfirebase.appspot.com',
    iosBundleId: 'com.example.blog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvggc7ZmlkIkoXJiZT_idPRAstA2b6eeg',
    appId: '1:775502867741:ios:95f6fe4004a2d88df585f4',
    messagingSenderId: '775502867741',
    projectId: 'bloguygfirebase',
    storageBucket: 'bloguygfirebase.appspot.com',
    iosBundleId: 'com.example.blog.RunnerTests',
  );
}
